services:
  backend:
    build: .
    volumes:
      - .:/var/www
    ports:
      - "8000:80"

  database_mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "33066:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
